# Generated by Django 4.1.1 on 2022-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200, null=True)),
                ('addr', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('phone1', models.CharField(max_length=200, null=True)),
                ('email1', models.CharField(max_length=200, null=True)),
                ('pass1', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
